
import type { Metadata } from 'next'
import { ProjectDataProvider } from '../contexts/ProjectDataContext'
import './globals.css'

import { Lato } from 'next/font/google'

const roboto = Lato({
	subsets: ['latin'],
	weight: ['100', '300', '400', '700', '900'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.className} antialiased`}>
				{' '}
				<ProjectDataProvider>{children}</ProjectDataProvider>
			</body>
		</html>
	)
}
